package ec.edu.ups.vista;

import ec.edu.ups.fabian.EN.ENTicket;
import ec.edu.ups.fabian.Gestion.GestionPaqueaderaRemoto;

import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Hashtable;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

public class InterfazCobrar extends javax.swing.JFrame {

	/**
	 * Creates new form InterfazCobrar
	 */
	GestionPaqueaderaRemoto gestionParqueadero;

	public InterfazCobrar() {
		initComponents();
		horaAutomatica();
		try {
			conectar();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		txthoraGuardada = new javax.swing.JTextField();
		txtHora = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		txtCodigo = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		txtTiempo = new javax.swing.JTextField();
		txtCosto = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		txthoraGuardada.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txthoraGuardadaActionPerformed(evt);
			}
		});

		jLabel1.setText("Hora Ingreso:");

		jLabel2.setText("Hora Salida:");

		jLabel3.setText("CÓDIGO DEL TICKET:");

		txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				txtCodigoKeyPressed(evt);
			}
		});

		jLabel4.setText("Tiempo:");

		jLabel5.setText("Costo:");

		jButton1.setText("COBRAR");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("SALIR");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		
		JLabel lblMensaje = new JLabel("");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(41)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel1)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jLabel4)
							.addGap(9)))
					.addGap(18)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(txthoraGuardada)
						.addComponent(txtCodigo)
						.addComponent(txtTiempo, GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
					.addPreferredGap(ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel2, Alignment.TRAILING)
						.addComponent(jLabel5, Alignment.TRAILING))
					.addGap(18)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(txtCosto, GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
						.addComponent(txtHora))
					.addGap(72))
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(274)
					.addComponent(jButton1)
					.addGap(54)
					.addComponent(jButton2)
					.addContainerGap(193, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(218)
					.addComponent(lblMensaje, GroupLayout.PREFERRED_SIZE, 240, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(237, Short.MAX_VALUE))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(49)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel3)
						.addComponent(txtCodigo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addGap(18)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(txthoraGuardada, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(txtHora, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel2)
						.addComponent(jLabel1))
					.addGap(18)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabel4)
						.addComponent(txtTiempo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(txtCosto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel5))
					.addGap(18)
					.addComponent(lblMensaje, GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
					.addGap(18)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))
					.addContainerGap())
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void txthoraGuardadaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
        VTNIngresoVehiculo v= new  VTNIngresoVehiculo();
        ENTicket t = new ENTicket();
        t.setTiHoraSalida(txtHora.getText());
        t.setTiCodigo(txtCodigo.getText());
        t.setTiCobro(Double.parseDouble(txtCosto.getText()));
        gestionParqueadero.actualizarTicket(t);
        this.setVisible(false);
	}

	private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:

		String tic = txtCodigo.getText();

        ENTicket t  = new ENTicket();
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
              t.setTiCodigo(txtCodigo.getText());
              gestionParqueadero.buscarTicK(t);
              txtCodigo.setText(gestionParqueadero.buscarTicK(t).getTiCodigo());
              txthoraGuardada.setText(gestionParqueadero.buscarTicK(t).getTiHoraIngreso());
              String a = gestionParqueadero.buscarTicK(t).getTiHoraIngreso();
              String b = txtHora.getText();
              gestionParqueadero.calcularTiempo(a, b);
              txtTiempo.setText(String.valueOf(gestionParqueadero.calcularTiempo(a, b)));
              txtCosto.setText(String.valueOf(gestionParqueadero.valorPagar(gestionParqueadero.calcularTiempo(a, b))));
		
		
	}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.setVisible(false);
		this.dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(InterfazCobrar.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(InterfazCobrar.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(InterfazCobrar.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(InterfazCobrar.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new InterfazCobrar().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField txtCodigo;
	private javax.swing.JTextField txtCosto;
	private javax.swing.JTextField txtHora;
	private javax.swing.JTextField txtTiempo;
	private javax.swing.JTextField txthoraGuardada;
	// End of variables declaration

	public void horaAutomatica() {
		Calendar c = new GregorianCalendar();
		int hora = c.get(Calendar.HOUR_OF_DAY);
		int minuto = c.get(Calendar.MINUTE);
		int segundo = c.get(Calendar.SECOND);
		txtHora.setText(hora + ":" + minuto + ":" + segundo);
	}
	
	public void conectar() throws Exception {
		try {  
            final Hashtable<String, Comparable> jndiProperties =  
                    new Hashtable<String, Comparable>(); 
          
            jndiProperties.put(Context.INITIAL_CONTEXT_FACTORY,  
                    "org.wildfly.naming.client.WildFlyInitialContextFactory");  
            jndiProperties.put("jboss.naming.client.ejb.context", true);  
              
            jndiProperties.put(Context.PROVIDER_URL, "http-remoting://localhost:8080");  
            jndiProperties.put(Context.SECURITY_PRINCIPAL, "ejb");  
            jndiProperties.put(Context.SECURITY_CREDENTIALS, "cuenca");  
              
            final Context context = new InitialContext(jndiProperties);  
              
            final String lookupName = "ejb:/Parqueadero/TicVeiON!ec.edu.ups.tobar.Gestion.GestionPaqueaderaRemoto";  
              
            this.gestionParqueadero = (GestionPaqueaderaRemoto) context.lookup(lookupName);  
              
        } catch (Exception ex) {  
            ex.printStackTrace();  
            throw ex; 
        
        }  
	}
}
